# Generated by Django 5.1.6 on 2025-03-24 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('cooking_duration', models.PositiveIntegerField(choices=[(5, '5 mins'), (10, '10 mins'), (15, '15 mins'), (20, '20 mins'), (25, '25 mins'), (30, '30 mins'), (35, '35 mins'), (40, '40 mins'), (45, '45 mins'), (50, '50 mins'), (55, '55 mins'), (60, '60 mins'), (65, '65 mins'), (70, '70 mins'), (75, '75 mins'), (80, '80 mins'), (85, '85 mins'), (90, '90 mins'), (95, '95 mins'), (100, '100 mins'), (105, '105 mins'), (110, '110 mins'), (115, '115 mins'), (120, '120 mins'), (125, '125 mins'), (130, '130 mins'), (135, '135 mins'), (140, '140 mins'), (145, '145 mins'), (150, '150 mins'), (155, '155 mins'), (160, '160 mins'), (165, '165 mins'), (170, '170 mins'), (175, '175 mins'), (180, '180 mins')], help_text='Cooking time in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
