# Generated by Django 5.1.7 on 2025-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measurement', models.CharField(choices=[('grams', 'grams'), ('ml', 'milliliters'), ('cup', 'cups'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('Oz', 'ounces')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.ingredient'),
        ),
    ]
