# Generated by Django 5.1.7 on 2025-04-12 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(choices=[('g', 'grams'), ('ml', 'milliliters'), ('cup', 'cups'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('oz', 'ounces'), ('large', 'large'), ('small', 'small')], max_length=50),
        ),
    ]
