# Generated by Django 5.1.7 on 2025-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='date',
        ),
        migrations.AddField(
            model_name='recipe',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-19T10:00:00'),
            preserve_default=False,
        ),
    ]
