# Generated by Django 5.1.7 on 2025-04-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_instructions_instructions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='instructions',
            new_name='Instruction',
        ),
    ]
