# Generated by Django 5.1.7 on 2025-05-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_instructions_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(choices=[('g', 'grams'), ('ml', 'milliliters'), ('l', 'litres'), ('cup', 'cups'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('oz', 'ounces'), ('large', 'large'), ('small', 'small'), ('slices', 'slices'), ('pints', 'pints'), ('pinches', 'pinches'), ('whole', 'whole'), ('half', 'half'), ('cloves', 'cloves'), ('sticks', 'sticks'), ('handfuls', 'handfuls'), ('knobs', 'knobs')], max_length=50),
        ),
    ]
